version: '3.8'

services:
  nats:
    image: nats-streaming:latest
    command: "--cluster_id cluster"
    ports:
      - "4222:4222"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: user1password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  order-service:
    build: .
    depends_on:
      - nats
      - postgres
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres://user1:user1password@postgres:5432/order_db
    volumes:
      - .:/app

volumes:
  postgres_data: